// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "custom"
import "jquery3"
import "popper"
import "bootstrap-sprockets"
import "rails-ujs"
import "turbolinks"
require "custom"
